### ISSUE TITLE
 no load X-Prison 1.16.0

### ISSUE THREAD

**Issue by ChicoIdeal** [Ale1x/X-Prison-Patched#1]
I have the latest version, I put it in MYSQL and Sqlite and I get this same error

Server version: 1.21

[00:50:59 INFO]: [X-Prison] Loaded 2 Pickaxe Levels.
[00:50:59 INFO]: [X-Prison] §aX-Prison - Module Pickaxe Levels loaded.
[00:50:59 INFO]: [X-Prison] §aX-Prison - Module History loaded.
[00:50:59 ERROR]: Error occurred while enabling X-Prison v1.16.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at XPrison-1.16.0.jar/dev.passarelli.xprison.XPrison.enable(XPrison.java:135) ~[XPrison-1.16.0.jar:?]
        at helper.jar/me.lucko.helper.plugin.ExtendedJavaPlugin.onEnable(ExtendedJavaPlugin.java:100) ~[helper.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[universe-1.21.jar:1.21-68f1122]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:203) ~[universe-1.21.jar:1.21-68f1122]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[universe-1.21.jar:1.21-68f1122]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[universe-1.21.jar:1.21-68f1122]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:643) ~[universe-1.21.jar:1.21-68f1122]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:592) ~[universe-1.21.jar:1.21-68f1122]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:760) ~[universe-1.21.jar:1.21-68f1122]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:522) ~[universe-1.21.jar:1.21-68f1122]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:341) ~[universe-1.21.jar:1.21-68f1122]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[universe-1.21.jar:1.21-68f1122]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:335) ~[universe-1.21.jar:1.21-68f1122]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: The name of the profile is longer than 16 characters
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.profile.CraftPlayerProfile.<init>(CraftPlayerProfile.java:67) ~[universe-1.21.jar:1.21-68f1122]
        at org.bukkit.craftbukkit.CraftServer.createPlayerProfile(CraftServer.java:2192) ~[universe-1.21.jar:1.21-68f1122]
        at org.bukkit.Bukkit.createPlayerProfile(Bukkit.java:1583) ~[universe-1.21.jar:1.21-68f1122]
        at XPrison-1.16.0.jar/dev.passarelli.xprison.utils.misc.SkullUtils.getProfile(SkullUtils.java:38) ~[XPrison-1.16.0.jar:?]
        at XPrison-1.16.0.jar/dev.passarelli.xprison.utils.misc.SkullUtils.getCustomTextureHead(SkullUtils.java:59) ~[XPrison-1.16.0.jar:?]
        at XPrison-1.16.0.jar/dev.passarelli.xprison.utils.misc.SkullUtils.<clinit>(SkullUtils.java:20) ~[XPrison-1.16.0.jar:?]
        ... 14 more

**Comment by Ale1x** [comment]
Hello @ChicoIdeal, can you share me your config.yml? Thank you!

**Comment by Ale1x** [comment]
Dropped a new release, everything should work fine now! @ChicoIdeal
