### ISSUE TITLE
Mass warnings while mine reset

### ISSUE THREAD

**Issue by shalostx** [Ale1x/X-Prison-Patched#4]
Server version: Purpur 1.21.1 (2329)
X-Prison: 1.17.0
helper: 5.6.14

[00:01:41] [Server thread/WARN]: java.lang.NoSuchMethodException: org.bukkit.block.Block.setData(byte)
[00:01:41] [Server thread/WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2395)
[00:01:41] [Server thread/WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getMethod(AbstractDefaultRulesReflectionProxy.java:100)
[00:01:41] [Server thread/WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getMethod(Unknown Source)
[00:01:41] [Server thread/WARN]:        at XPrison-1.17.0.jar//dev.passarelli.xprison.mines.model.mine.reset.GradualReset.lambda$schedule$0(GradualReset.java:45)
[00:01:41] [Server thread/WARN]:        at helper (3).jar//me.lucko.helper.utils.Delegates$RunnableToSupplier.get(Delegates.java:127)
[00:01:41] [Server thread/WARN]:        at helper (3).jar//me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:672)
[00:01:41] [Server thread/WARN]:        at helper (3).jar//me.lucko.helper.internal.exception.HelperExceptions$SchedulerWrappedRunnable.run(HelperExceptions.java:89)
[00:01:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[00:01:41] [Server thread/WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[00:01:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1770)
[00:01:41] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513)
[00:01:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642)
[00:01:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342)
[00:01:41] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
[00:01:41] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by Ale1x** [comment]
Hello, could you send full log on discord?

My ID is: "alee1x"
